version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/to-do-list

permissions:
  - object: /home/ubuntu/to-do-list
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ubuntu
  
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 60
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ubuntu
